# Generated by Django 5.2.5 on 2026-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('seat_id', models.IntegerField(blank=True, null=True, verbose_name='工位ID')),
                ('seat_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='工位编号')),
                ('operation_type', models.SmallIntegerField(choices=[(1, '创建工位'), (2, '绑定人员'), (3, '解绑人员'), (4, '更换工位'), (5, '额外绑定'), (6, '批量生成工位'), (7, '修改工位信息'), (8, '删除工位'), (9, 'OA系统同步')], verbose_name='操作类型')),
                ('old_user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='原人员ID')),
                ('old_user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='原人员姓名')),
                ('new_user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='新人员ID')),
                ('new_user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='新人员姓名')),
                ('operator_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人ID')),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人姓名')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作IP')),
                ('operation_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='操作备注')),
                ('extra_info', models.JSONField(blank=True, null=True, verbose_name='额外信息')),
            ],
            options={
                'verbose_name': '工位变更日志',
                'verbose_name_plural': '工位变更日志',
                'ordering': ['-operation_time'],
            },
        ),
    ]
