# Generated by Django 5.2.5 on 2026-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='场地名称')),
                ('address', models.CharField(max_length=200, verbose_name='场地地址')),
                ('status', models.SmallIntegerField(default=1, help_text='0:停用, 1:启用', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
            },
        ),
    ]
