# Generated by Django 5.2.5 on 2026-01-27 11:20

from django.db import migrations, models


def generate_unique_codes(apps, schema_editor):
    """
    为现有场地生成唯一的编码
    """
    Venue = apps.get_model('venues', 'Venue')
    for i, venue in enumerate(Venue.objects.all()):
        # 为每个场地生成唯一的编码，使用场地名称的拼音首字母 + 数字
        venue.code = f'venue_{i+1}'
        venue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        # 1. 先添加允许为空的字段
        migrations.AddField(
            model_name='venue',
            name='code',
            field=models.CharField(max_length=20, null=True, blank=True, verbose_name='场地编码'),
            preserve_default=False,
        ),
        # 2. 为现有记录填充值
        migrations.RunPython(generate_unique_codes),
        # 3. 修改字段为非空且唯一
        migrations.AlterField(
            model_name='venue',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='场地编码'),
        ),
    ]
