# Generated by Django 5.2.5 on 2026-01-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default=12345, max_length=50, verbose_name='所在城市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='floorCount',
            field=models.IntegerField(default=1, verbose_name='楼层数'),
        ),
        migrations.AddField(
            model_name='venue',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注说明'),
        ),
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.CharField(default='租赁办公', max_length=50, verbose_name='场地类型'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=200, verbose_name='详细地址'),
        ),
    ]
