# Generated by Django 5.2.5 on 2026-01-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_no', models.CharField(help_text='如：101, 102', max_length=20, verbose_name='区域编号')),
                ('area_name', models.CharField(max_length=50, verbose_name='区域名称')),
                ('area_type', models.SmallIntegerField(default=1, help_text='1:专属区, 2:混合区, 3:会议室, 4:公共区', verbose_name='区域类型')),
                ('allowed_depts', models.TextField(default='[]', help_text='JSON格式，如：["D01", "D02"]', verbose_name='允许的部门ID列表')),
                ('seat_count', models.IntegerField(default=0, verbose_name='计划工位数')),
                ('position_css', models.TextField(default='{}', help_text='JSON格式，如：{"top": "10px", "left": "10px", "width": "100px", "height": "100px"}', verbose_name='位置样式')),
                ('status', models.SmallIntegerField(default=1, help_text='0:停用, 1:启用', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_set', to='floors.floor', verbose_name='所属楼层')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'unique_together': {('floor', 'area_no')},
            },
        ),
    ]
