# Generated by Django 5.2.5 on 2026-01-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(help_text='如：101-1, 102-2', max_length=20, verbose_name='工位编号')),
                ('seat_status', models.SmallIntegerField(default=0, help_text='0:闲置, 1:占用, 2:维修中, 3:停用', verbose_name='工位状态')),
                ('grid_row', models.IntegerField(default=0, verbose_name='网格行号')),
                ('grid_col', models.IntegerField(default=0, verbose_name='网格列号')),
                ('position_x', models.FloatField(default=0.0, help_text='0-1之间的值', verbose_name='相对坐标X')),
                ('position_y', models.FloatField(default=0.0, help_text='0-1之间的值', verbose_name='相对坐标Y')),
                ('current_user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='当前绑定人员ID（OA工号）')),
                ('current_user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='人员姓名（冗余）')),
                ('current_dept_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='部门ID（冗余）')),
                ('bind_type', models.SmallIntegerField(default=0, help_text='0:未绑定, 1:主工位, 2:额外绑定', verbose_name='绑定类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_set', to='areas.area', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '工位',
                'verbose_name_plural': '工位',
                'unique_together': {('area', 'seat_no')},
            },
        ),
    ]
