# Generated by Django 5.2.5 on 2026-01-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.CharField(help_text='如：1F, 2F', max_length=10, verbose_name='楼层编号')),
                ('floor_name', models.CharField(max_length=50, verbose_name='楼层名称')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='平面图URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('status', models.SmallIntegerField(default=1, help_text='0:停用, 1:启用', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_set', to='venues.venue', verbose_name='所属场地')),
            ],
            options={
                'verbose_name': '楼层',
                'verbose_name_plural': '楼层',
                'unique_together': {('venue', 'floor_no')},
            },
        ),
    ]
