# Generated by Django 5.2.5 on 2026-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='人员ID（OA工号）')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('dept_id', models.CharField(max_length=50, verbose_name='部门ID')),
                ('dept_name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('status', models.SmallIntegerField(default=1, help_text='0:离职, 1:在职', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
    ]
